Return-Path: <linux-clk-owner@vger.kernel.org>
X-Original-To: lists+linux-clk@lfdr.de
Delivered-To: lists+linux-clk@lfdr.de
Received: from out1.vger.email (out1.vger.email [IPv6:2620:137:e000::1:20])
	by mail.lfdr.de (Postfix) with ESMTP id B956D58D859
	for <lists+linux-clk@lfdr.de>; Tue,  9 Aug 2022 13:46:17 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S242480AbiHILqQ (ORCPT <rfc822;lists+linux-clk@lfdr.de>);
        Tue, 9 Aug 2022 07:46:16 -0400
Received: from lindbergh.monkeyblade.net ([23.128.96.19]:36356 "EHLO
        lindbergh.monkeyblade.net" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S242197AbiHILqO (ORCPT
        <rfc822;linux-clk@vger.kernel.org>); Tue, 9 Aug 2022 07:46:14 -0400
Received: from mail-lj1-x236.google.com (mail-lj1-x236.google.com [IPv6:2a00:1450:4864:20::236])
        by lindbergh.monkeyblade.net (Postfix) with ESMTPS id DD111248D1
        for <linux-clk@vger.kernel.org>; Tue,  9 Aug 2022 04:46:12 -0700 (PDT)
Received: by mail-lj1-x236.google.com with SMTP id l10so8117168lje.7
        for <linux-clk@vger.kernel.org>; Tue, 09 Aug 2022 04:46:12 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=linaro.org; s=google;
        h=cc:to:subject:message-id:date:from:in-reply-to:references
         :mime-version:from:to:cc;
        bh=QsmUqL/K7yU3SMzZ0FTopGj6zj1tOvzFKhz171z4vRY=;
        b=QTHzvwv/41mQMSEBfjxOTjKs8N4fwJGEfzsaCC0mt/Ihiv3I3PcDjCpAmjDTbs/uxF
         EIn0/mCBPJTSgtJ9ICMCNob8aGvq6IUlcNqhH5EbJliIytnq1AY+nL9nr1QZ+Bedc31v
         NlDQf0q31jKIfztN03g1jZxVeAiLIsLNxqJxg3HK2vkS6i8TNHvqGap0+MOHhxL5bRwK
         13POO0aAlCuOhu8p7ZTlPoPj/K8v40sLuvINWM6DyDlHldBkLUU92pHrWgjTV7x9B7C/
         J8pjg0kDs46WT1AwPDzQYQrBguHsRBBZZDkbpzvoZS7cyVx+PkUZxkUU5ernSavqaQ4u
         x6vQ==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20210112;
        h=cc:to:subject:message-id:date:from:in-reply-to:references
         :mime-version:x-gm-message-state:from:to:cc;
        bh=QsmUqL/K7yU3SMzZ0FTopGj6zj1tOvzFKhz171z4vRY=;
        b=jDT9ZLsAl3KgvvYXRxjthEFn8VzYcDMDWtD0b9GC1eHrRCKjHcvcmMta3iqknQjZ6X
         rFtvxMSdVtTTkwKXs6AsxuJ9imnxVNYFq3DYjFyFZYjA6TjVrJyQCGqAEKX9IVc+9Q29
         sBNkjOFxvHJ/ysM8jqswR2m2G21TMS+wO0rGlwk81cNUXyEICo5Jfa2GMABuT4xisW+L
         V4jJ80H6sMmSFzn+aXongkjD/k8BDhV42Su3NqvyAuFOebfBc0CBJowfYoJ1ILTTRuCR
         AImzCvdapIV/FwWmRpPrZDIoEIt+loxm9IF8bX4tBaIui9Tpo5JKQfGuZweWIxOXShna
         /oYw==
X-Gm-Message-State: ACgBeo1kJ7OgsBWfZpxHJ2oD5Vc+pjzCqAGLdm8VfTQhMWhES/TpKyfV
        CV6B54IVUjL3VVtfWXc+Uf0SbbeNSOqVNw2Og3WgBA==
X-Google-Smtp-Source: AA6agR64z/0ZB46ZAz00rHuh7z2Dk81PNldSaQZLPyWTwsm2PmcCZAGxyQg2VQnsxR5Tdof9+9x2LT0E/6IFrcwwqFk=
X-Received: by 2002:a2e:a4d6:0:b0:25e:439e:39d0 with SMTP id
 p22-20020a2ea4d6000000b0025e439e39d0mr7029084ljm.169.1660045571001; Tue, 09
 Aug 2022 04:46:11 -0700 (PDT)
MIME-Version: 1.0
References: <20220808181555.10333-1-semen.protsenko@linaro.org>
In-Reply-To: <20220808181555.10333-1-semen.protsenko@linaro.org>
From:   Sam Protsenko <semen.protsenko@linaro.org>
Date:   Tue, 9 Aug 2022 14:45:59 +0300
Message-ID: <CAPLW+4nFzxa6gH_uxRuypWFS3WzrENS5Wz5j32L6q53T7eZG_Q@mail.gmail.com>
Subject: Re: [PATCH 0/7] clk: samsung: exynos850: Add CMUs needed for SysMMU
To:     Sylwester Nawrocki <s.nawrocki@samsung.com>,
        Krzysztof Kozlowski <krzk@kernel.org>,
        Rob Herring <robh+dt@kernel.org>,
        Chanwoo Choi <cw00.choi@samsung.com>
Cc:     Tomasz Figa <tomasz.figa@gmail.com>,
        Alim Akhtar <alim.akhtar@samsung.com>,
        Michael Turquette <mturquette@baylibre.com>,
        Stephen Boyd <sboyd@kernel.org>,
        Sumit Semwal <sumit.semwal@linaro.org>,
        linux-samsung-soc@vger.kernel.org, linux-clk@vger.kernel.org,
        devicetree@vger.kernel.org, linux-arm-kernel@lists.infradead.org,
        linux-kernel@vger.kernel.org
Content-Type: text/plain; charset="UTF-8"
X-Spam-Status: No, score=-2.1 required=5.0 tests=BAYES_00,DKIM_SIGNED,
        DKIM_VALID,DKIM_VALID_AU,DKIM_VALID_EF,RCVD_IN_DNSWL_NONE,
        SPF_HELO_NONE,SPF_PASS,T_SCC_BODY_TEXT_LINE autolearn=unavailable
        autolearn_force=no version=3.4.6
X-Spam-Checker-Version: SpamAssassin 3.4.6 (2021-04-09) on
        lindbergh.monkeyblade.net
Precedence: bulk
List-ID: <linux-clk.vger.kernel.org>
X-Mailing-List: linux-clk@vger.kernel.org

On Mon, 8 Aug 2022 at 21:15, Sam Protsenko <semen.protsenko@linaro.org> wrote:
>
> This patch series implements some missing Exynos850 clock domains. Right
> now those are mainly required for SysMMU clocks, although of course
> there is a lot of other clocks generated by those CMUs.
>
> Exynos850 has next SysMMU instances:
>   - SYSMMU_AUD
>   - SYSMMU_DPU
>   - SYSMMU_IS0
>   - SYSMMU_IS1
>   - SYSMMU_MFCMSCL
>
> As CMU_DPU is already implemented, that leaves CMU_AUD, CMU_IS and
> CMU_MFCMSCL to be implemented, which is done in this series:
>   - CMU_AUD: audio clocks
>   - CMU_IS: camera clocks (Image Signal Processing)
>   - CMU_MFCMSCL: multi-format codec and scaler clocks
>
> Sam Protsenko (7):
>   dt-bindings: clock: Add bindings for Exynos850 CMU_AUD
>   dt-bindings: clock: Add bindings for Exynos850 CMU_IS
>   dt-bindings: clock: Add bindings for Exynos850 CMU_MFCMSCL
>   clk: samsung: exynos850: Style fixes
>   clk: samsung: exynos850: Implement CMU_AUD domain
>   clk: samsung: exynos850: Implement CMU_IS domain
>   clk: samsung: exynos850: Implement CMU_MFCMSCL domain
>
>  .../clock/samsung,exynos850-clock.yaml        |  69 ++
>  drivers/clk/samsung/clk-exynos850.c           | 682 +++++++++++++++++-
>  include/dt-bindings/clock/exynos850.h         | 136 +++-
>  3 files changed, 883 insertions(+), 4 deletions(-)
>
> --
> 2.30.2
>

This patch series is superseded by v2 here: [1].

[1] https://lkml.org/lkml/2022/8/9/328
